//! The deterministic STATE layer.
//!
//! The rule that decides what lives here is `agent_state.py`'s boundary rule,
//! and it is the same one the plan uses: *if a function can compute it from raw
//! event data, it's Layer 2.* Nothing in this crate calls a model. The one
//! place the daemon does — the narrative summary for a project flush — is a
//! trait the caller injects ([`multi_agent::ProjectSummarizer`]), with the
//! deterministic template fallback ported exactly.
//!
//! | module | Python | what it owns |
//! |---|---|---|
//! | [`agent_state`] | `heard/agent_state.py` | the per-agent scoreboard: facts + cheap heuristic hints |
//! | [`session`] | `heard/session.py` | the daemon's tiny per-session bookkeeping |
//! | [`multi_agent`] | `heard/multi_agent.py` | Solo / Swarm / Pinned routing + the project-keyed channel scheduler |
//! | [`spoken`] | `heard/spoken.py` | per-session dedup of already-narrated text, flock'd |
//! | [`history`] | `heard/history.py` | the append-only spoken-history JSONL |
//!
//! Supporting modules: [`clock`] (time, injected), [`project_name`] (the single
//! source of truth for a project's spoken name), [`event`] (the hook payload),
//! [`pyjson`] (CPython-compatible JSON, for byte-identical history lines) and
//! [`sha1`] (pinned by two on-disk formats).
//!
//! ## Determinism, and why the whole crate takes its clock as a parameter
//!
//! The golden corpus is what turns "did I port this correctly?" into a
//! failing test. That only works if the port is a function
//! of its inputs, so every module here takes its clock, its project namer and
//! its config directory as constructor arguments rather than reading a global.
//! `fixtures/state/*.json` is generated by the fixture generator (not
//! included) from cases lifted out of the Python reference implementation's
//! tests; `tests/fixtures.rs` replays it here, and the reference re-asserts it
//! on its side, so neither can drift without the other noticing.
//!
//! ## Two divergences this port found — both now fixed on BOTH sides
//!
//! * `AgentState::files_touched` keeps touch order (a `Vec` here, a list in
//!   Python). Python used a `set`, whose iteration order is salted per
//!   process, which made `_derived_area`'s tie-break and `to_dict`'s
//!   `files_touched_recent` irreproducible — and made "recent" mean "an
//!   arbitrary five". Both sides now resolve an area tie in favour of the
//!   directory touched FIRST and slice the genuinely five most recent files.
//!   See [`agent_state`].
//! * `SpokenStore`'s save writes a tmp file and renames, and so does Python's
//!   `_save` now. It used to truncate in place while every reader
//!   (`is_spoken`, `filter_unspoken`) holds no lock, so a reader inside that
//!   window saw an empty file and the text was narrated twice — the bug the
//!   flock exists to prevent, arriving through the read path. The final bytes
//!   are identical either way. See [`spoken`].
//!
//! ## Not here
//!
//! LLM-shaped memory (a background compressor, an episode summarizer) is
//! deliberately out of scope: it belongs with a provider, not with the
//! deterministic layer. It attaches from outside through the daemon's
//! extension seam.

pub mod agent_state;
pub mod clock;
pub mod event;
pub mod history;
pub mod history_policy;
pub mod jsonl;
pub mod multi_agent;
pub mod project_name;
pub mod py;
pub mod pyjson;
pub mod session;
pub mod session_identity;
pub mod sha1;
pub mod spoken;

pub use agent_state::{AgentState, AgentStateRegistry, ResponseShape, Salience};
pub use clock::{Clock, ManualClock, SystemClock};
pub use event::{AgentEvent, EventKind};
pub use history::History;
pub use history_policy::{HistoryPolicy, HistoryPolicySource};
pub use multi_agent::{
    Action, Mode, MultiAgentRouter, ProjectFlush, ProjectSummarizer, RoutingDecision, TemplateOnly,
};
pub use project_name::{BasenameProjectNamer, GitProjectNamer, ProjectNamer};
pub use session::SessionStore;
pub use session_identity::{SessionIdentity, SessionIdentityRegistry};
pub use spoken::SpokenStore;
