//! The silence trim against the real `kokoro_onnx.trim`, sample for sample.
//!
//! `fixtures/speech/trim.json` is generated by the fixture generator (not
//! included), which runs `kokoro_onnx.trim.trim` /
//! `rms` / `amplitude_to_db` on int16-valued signals (exact in float32 on both
//! sides). Each case pins the cut interval, the trimmed length, the RMS of
//! every frame (bit-exact) and the dB of every frame (to a float32 ulp or so —
//! `log10f` is the platform's on both sides).

use std::fs;
use std::path::PathBuf;

use heard_tts::trim;
use serde_json::Value;

fn corpus() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/speech/trim.json");
    serde_json::from_str(&fs::read_to_string(path).expect("trim corpus")).expect("json")
}

#[test]
fn every_case_cuts_exactly_where_kokoro_onnx_cuts() {
    let data = corpus();
    let scale = data["scale"].as_f64().unwrap() as f32;
    let cases = data["cases"].as_array().unwrap();
    assert!(cases.len() >= 9);
    let mut before = 0usize;
    let mut after = 0usize;
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let y: Vec<f32> = case["samples_i16"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_i64().unwrap() as f32 / scale)
            .collect();
        assert_eq!(y.len(), case["n"].as_u64().unwrap() as usize, "{name}");

        let rms = trim::rms(&y, trim::FRAME_LENGTH, trim::HOP_LENGTH);
        let want_rms: Vec<f32> = case["rms"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        assert_eq!(
            rms, want_rms,
            "{name}: per-frame RMS must be bit-identical to NumPy's"
        );

        let db = trim::amplitude_to_db(&rms);
        for (i, (got, want)) in db.iter().zip(case["db"].as_array().unwrap()).enumerate() {
            let want = want.as_f64().unwrap() as f32;
            assert!(
                (got - want).abs() <= 1e-4,
                "{name}: frame {i} dB {got} vs {want}"
            );
        }

        let (start, end) = trim::trim_interval(&y);
        assert_eq!(
            (start, end),
            (
                case["start"].as_u64().unwrap() as usize,
                case["end"].as_u64().unwrap() as usize
            ),
            "{name}"
        );
        assert_eq!(
            trim::trim(&y).len(),
            case["trimmed_len"].as_u64().unwrap() as usize,
            "{name}"
        );
        before += y.len();
        after += end - start;
    }
    // The before/after the spike lane asked for, over the whole corpus.
    eprintln!("trim corpus: {before} samples in, {after} out");
    assert!(after < before);
}
