//! The golden corpus: this port must agree with the Python, record for record.
//!
//! The JSON is generated by the fixture generator (not included) from the
//! inputs of the Python reference implementation's tests, and the reference
//! re-asserts every record on its side.
//!
//! A failure prints the case name, the input and both sides — the case names
//! are stable, so a diff here names exactly which behaviour moved.

use std::fs;
use std::path::PathBuf;

use serde_json::{json, Value};

use heard_narrate::templates::{self, Narration};
use heard_narrate::{markdown, verbosity};

fn corpus(module: &str) -> Vec<Value> {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "fixtures",
        "narrate",
    ]
    .iter()
    .collect::<PathBuf>()
    .join(format!("{module}.json"));
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing corpus {}: {e} — regenerate it with the fixture generator",
            path.display()
        )
    });
    match serde_json::from_str(&raw).expect("corpus is not valid JSON") {
        Value::Array(cases) => cases,
        _ => panic!("corpus must be a list of cases"),
    }
}

fn check(module: &str, run: impl Fn(&Value) -> Value) {
    let cases = corpus(module);
    assert!(
        cases.len() >= 50,
        "{module}: a corpus this small proves nothing"
    );
    let mut failures = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap_or("?");
        let got = run(&case["input"]);
        let want = &case["output"];
        if &got != want {
            failures.push(format!(
                "  {name}\n    input:  {}\n    python: {want}\n    rust:   {got}",
                case["input"]
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{module}: {} of {} cases diverge from Python:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

#[test]
fn markdown_matches_python() {
    check("markdown", |input| {
        Value::String(
            markdown::strip(input.as_str().expect("markdown input is a string")).into_owned(),
        )
    });
}

fn narration_json(n: Option<Narration<'_>>) -> Value {
    match n {
        None => Value::Null,
        Some(n) => json!({"tag": n.tag, "text": n.text, "ctx": n.ctx_json()}),
    }
}

#[test]
fn templates_match_python() {
    check("templates", |input| {
        let f = input["fn"].as_str().expect("case names a function");
        match f {
            "pre_tool_event" => narration_json(templates::pre_tool_event(
                input["tool"].as_str().unwrap_or(""),
                &input["input"],
            )),
            "post_tool_event" => narration_json(templates::post_tool_event(
                input["tool"].as_str().unwrap_or(""),
                &input["response"],
            )),
            "bash_tag_and_text" => {
                let (tag, text) = templates::bash_tag_and_text(
                    input["command"].as_str(),
                    input["description"].as_str(),
                );
                json!({"tag": tag, "text": text})
            }
            "first_token" => Value::String(
                templates::first_token(input["command"].as_str().unwrap_or("")).to_owned(),
            ),
            "present_continuous" => Value::String(
                templates::present_continuous(input["text"].as_str().unwrap_or("")).into_owned(),
            ),
            "needs_you_line" => {
                match templates::needs_you_line(input["text"].as_str().unwrap_or("")) {
                    Some(line) => Value::String(line.into_owned()),
                    None => Value::Null,
                }
            }
            other => panic!("unknown template fn {other:?}"),
        }
    });
}

#[test]
fn verbosity_matches_python() {
    check("verbosity", |input| {
        let cfg = verbosity::Cfg(&input["cfg"]);
        let f = input["fn"].as_str().expect("case names a function");
        let out = match f {
            "level" => verbosity::level(&cfg),
            "classify_pre" => verbosity::classify_pre(
                &cfg,
                input["tag"].as_str().unwrap_or(""),
                input["density"].as_i64().unwrap_or(0),
            )
            .as_str()
            .to_owned(),
            "classify_post" => verbosity::classify_post(&cfg, input["tag"].as_str().unwrap_or(""))
                .as_str()
                .to_owned(),
            "classify_prose" => verbosity::classify_prose(&cfg).as_str().to_owned(),
            other => panic!("unknown verbosity fn {other:?}"),
        };
        Value::String(out)
    });
}
