//! The golden corpus, replayed against the Rust port.
//!
//! This turns "was it ported correctly?" from a reading exercise into a
//! failing test. The files under `fixtures/state/` are generated by the
//! fixture generator (not included) from cases lifted out of the Python
//! reference implementation's test suite; the reference re-asserts that it
//! still produces them, and this file asserts that the Rust does too. Neither
//! implementation can move without the other failing.
//!
//! Every case here is a Python behaviour, including the ones that are arguably
//! wrong ("A edit." rather than "An edit."). The plan names this explicitly as
//! risk 4: a fixture pins CURRENT behaviour and is not a judgement about
//! whether the behaviour is right. Disagreements are reported, not silently
//! corrected.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::Arc;

use heard_state::agent_state::{
    approx_tokens, compute_response_shape_hint, compute_salience_hint, tool_name_from_tag,
    AgentSnapshot, AgentState, AgentStateRegistry, NoLabel,
};
use heard_state::clock::ManualClock;
use heard_state::event::AgentEvent;
use heard_state::history::History;
use heard_state::multi_agent::{
    auto_voice_for, format_project_summary, DigestEvent, MultiAgentRouter, ProjectRootFinder,
};
use heard_state::project_name::{BasenameProjectNamer, GitProjectNamer};
use heard_state::pyjson::{record_from_fixture, PyValue};
use heard_state::session::SessionStore;
use heard_state::spoken::SpokenStore;
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/state")
        .join(name);
    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{} — run `python3 -m tools.fixtures_state` from engine/: {e}",
            path.display()
        )
    });
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()))
}

fn scratch(tag: &str) -> PathBuf {
    static COUNTER: AtomicU32 = AtomicU32::new(0);
    let n = COUNTER.fetch_add(1, Ordering::SeqCst);
    let dir = std::env::temp_dir().join(format!(
        "heard-state-fixtures-{tag}-{}-{n}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

fn as_str(value: &Value) -> &str {
    value.as_str().unwrap_or_default()
}

fn opt_string(value: &Value) -> Option<String> {
    value.as_str().map(str::to_string)
}

// ---------------------------------------------------------------------------
// agent_state
// ---------------------------------------------------------------------------

#[test]
fn agent_state_helper_tables_match() {
    let data = fixture("agent_state.json");

    for case in data["tool_name_from_tag"].as_array().expect("array") {
        let tag = as_str(&case["tag"]);
        assert_eq!(
            tool_name_from_tag(tag),
            opt_string(&case["expect"]),
            "tool_name_from_tag({tag:?})"
        );
    }

    for case in data["approx_tokens"].as_array().expect("array") {
        let chars = case["chars"].as_u64().expect("chars") as usize;
        let text = "x".repeat(chars);
        assert_eq!(
            approx_tokens(&text) as u64,
            case["expect"].as_u64().expect("expect"),
            "approx_tokens over {chars} chars"
        );
    }

    for case in data["response_shape_hint"].as_array().expect("array") {
        let window: std::collections::VecDeque<usize> = case["window"]
            .as_array()
            .expect("window")
            .iter()
            .map(|v| v.as_u64().expect("token count") as usize)
            .collect();
        assert_eq!(
            compute_response_shape_hint(&window).as_str(),
            as_str(&case["expect"]),
            "response shape over {window:?}"
        );
    }

    for case in data["salience_hint"].as_array().expect("array") {
        let mut state = AgentState::new("probe", 0.0, 0.0);
        state.error_count = case["error_count"].as_u64().expect("error_count");
        state.event_count = case["event_count"].as_u64().expect("event_count");
        state.current_tool = opt_string(&case["current_tool"]);
        state.recent_output_tokens = case["window"]
            .as_array()
            .expect("window")
            .iter()
            .map(|v| v.as_u64().expect("token count") as usize)
            .collect();
        state.last_event_at = 0.0;
        let now = case["idle_seconds"].as_f64().expect("idle_seconds");
        assert_eq!(
            compute_salience_hint(&state, now).as_str(),
            as_str(&case["expect"]),
            "salience for {case}"
        );
    }
}

#[test]
fn agent_state_sequences_match() {
    let data = fixture("agent_state.json");
    for case in data["sequences"].as_array().expect("array") {
        let name = as_str(&case["name"]);
        // A ManualClock keeps `last_tool_duration_s` and the idle window
        // reproducible; the snapshot only records presence, but the salience
        // hint reads the idle window, so the clock has to be still.
        let clock = Arc::new(ManualClock::new(1_000_000.0));
        let registry =
            AgentStateRegistry::with(clock, Arc::new(BasenameProjectNamer), Arc::new(NoLabel));
        for raw in case["events"].as_array().expect("events") {
            let event: AgentEvent =
                serde_json::from_value(raw.clone()).unwrap_or_else(|e| panic!("{name}: {e}"));
            registry.observe(&event);
        }
        let expected: HashMap<String, AgentSnapshot> =
            serde_json::from_value(case["expect"].clone())
                .unwrap_or_else(|e| panic!("{name}: expectation does not parse: {e}"));
        let actual: HashMap<String, AgentSnapshot> = registry
            .all()
            .iter()
            .map(|a| (a.id.clone(), a.snapshot()))
            .collect();
        assert_eq!(actual, expected, "agent_state sequence {name}");
    }
}

#[test]
fn agent_state_repo_names_survive_the_real_git_namer() {
    // The corpus was generated with the production namer, which shells out to
    // `git remote get-url origin`. Every fixture path is non-existent, so both
    // languages take the basename branch — this pins that, so a future corpus
    // built inside a checkout would fail loudly instead of quietly encoding one
    // machine's remotes.
    let data = fixture("agent_state.json");
    let clock = Arc::new(ManualClock::new(1_000_000.0));
    let registry =
        AgentStateRegistry::with(clock, Arc::new(GitProjectNamer::new()), Arc::new(NoLabel));
    let case = data["sequences"]
        .as_array()
        .expect("array")
        .iter()
        .find(|c| as_str(&c["name"]) == "first_event_creates_agent_with_cwd_and_repo_name")
        .expect("the cwd case is in the corpus");
    for raw in case["events"].as_array().expect("events") {
        let event: AgentEvent = serde_json::from_value(raw.clone()).expect("event");
        registry.observe(&event);
    }
    assert_eq!(
        registry.get("s1").expect("agent").repo_name.as_deref(),
        Some("heard")
    );
}

// ---------------------------------------------------------------------------
// session
// ---------------------------------------------------------------------------

#[test]
fn session_scripts_match() {
    let data = fixture("session.json");
    let start = data["start_time"].as_f64().expect("start_time");
    for script in data["scripts"].as_array().expect("scripts") {
        let name = as_str(&script["name"]);
        let clock = Arc::new(ManualClock::new(start));
        let store = SessionStore::with_clock(clock.clone());
        let mut trace: Vec<Value> = Vec::new();
        for op in script["ops"].as_array().expect("ops") {
            match as_str(&op["op"]) {
                "advance" => clock.advance(op["seconds"].as_f64().expect("seconds")),
                "touch" => {
                    let view = store.touch(
                        as_str(&op["session_id"]),
                        op.get("cwd").and_then(Value::as_str),
                    );
                    trace.push(session_view_pairs(&view));
                }
                "get" => {
                    let view = store.get(as_str(&op["session_id"]));
                    trace.push(session_view_pairs(&view));
                }
                "note_failure" => store.note_failure(as_str(&op["session_id"])),
                "note_topic" => store.note_topic(as_str(&op["session_id"]), as_str(&op["topic"])),
                "record_tool_event" => store.record_tool_event(as_str(&op["session_id"])),
                "tool_density" => {
                    trace.push(Value::from(store.tool_density(as_str(&op["session_id"]))))
                }
                other => panic!("{name}: unknown session op {other:?}"),
            }
        }
        assert_eq!(
            Value::Array(trace),
            script["trace"],
            "session script {name}"
        );
    }
}

/// `SessionView` back into the ordered-pairs shape the corpus records, which is
/// the Python dict's own insertion order: repo_name, failure_count, last_topic,
/// last_seen. An unknown session is `{}` — an empty pair list.
fn session_view_pairs(view: &heard_state::session::SessionView) -> Value {
    let Some(last_seen) = view.last_seen else {
        return Value::Array(vec![]);
    };
    Value::Array(vec![
        Value::Array(vec![
            Value::from("repo_name"),
            match &view.repo_name {
                Some(name) => Value::from(name.clone()),
                None => Value::Null,
            },
        ]),
        Value::Array(vec![
            Value::from("failure_count"),
            Value::from(view.failure_count),
        ]),
        Value::Array(vec![
            Value::from("last_topic"),
            match &view.last_topic {
                Some(topic) => Value::from(topic.clone()),
                None => Value::Null,
            },
        ]),
        Value::Array(vec![Value::from("last_seen"), Value::from(last_seen)]),
    ])
}

// ---------------------------------------------------------------------------
// multi_agent
// ---------------------------------------------------------------------------

#[test]
fn multi_agent_constants_and_tables_match() {
    let data = fixture("multi_agent.json");
    let pool: Vec<String> = serde_json::from_value(data["auto_voice_pool"].clone()).expect("pool");
    assert_eq!(pool, heard_state::multi_agent::AUTO_VOICE_POOL.to_vec());
    assert_eq!(
        data["session_active_s"].as_f64(),
        Some(heard_state::multi_agent::SESSION_ACTIVE_S)
    );
    assert_eq!(
        data["session_visible_s"].as_f64(),
        Some(heard_state::multi_agent::SESSION_VISIBLE_S)
    );
    assert_eq!(
        data["channel_idle_flush_s"].as_f64(),
        Some(heard_state::multi_agent::CHANNEL_IDLE_FLUSH_S)
    );
    assert_eq!(
        data["channel_max_pending"].as_u64(),
        Some(heard_state::multi_agent::CHANNEL_MAX_PENDING as u64)
    );

    for case in data["auto_voice_for"].as_array().expect("array") {
        let repo = as_str(&case["repo_name"]);
        assert_eq!(
            auto_voice_for(repo),
            as_str(&case["expect"]),
            "auto_voice_for({repo:?})"
        );
    }

    for case in data["format_project_summary"].as_array().expect("array") {
        let events: Vec<DigestEvent> = case["tags"]
            .as_array()
            .expect("tags")
            .iter()
            .enumerate()
            .map(|(i, tag)| DigestEvent {
                kind: String::new(),
                tag: as_str(tag).to_string(),
                neutral: String::new(),
                ctx: Value::Null,
                ts: i as f64,
            })
            .collect();
        let got = format_project_summary(
            as_str(&case["label"]),
            &events,
            case["member_count"].as_u64().expect("member_count") as usize,
            case["include_label"].as_bool().expect("include_label"),
        );
        assert_eq!(
            got,
            opt_string(&case["expect"]),
            "format_project_summary {case}"
        );
    }
}

#[test]
fn multi_agent_scripts_match() {
    let data = fixture("multi_agent.json");
    for script in data["scripts"].as_array().expect("scripts") {
        let name = as_str(&script["name"]);
        let start = script["start_time"].as_f64().expect("start_time");
        let clock = Arc::new(ManualClock::new(start));
        let router = MultiAgentRouter::with(clock.clone(), Arc::new(BasenameProjectNamer));
        let mut trace: Vec<Value> = Vec::new();
        for op in script["ops"].as_array().expect("ops") {
            match as_str(&op["op"]) {
                "advance" => clock.advance(op["seconds"].as_f64().expect("seconds")),
                "note_event" => router.note_event(
                    as_str(&op["session_id"]),
                    op.get("cwd").and_then(Value::as_str).unwrap_or(""),
                    op.get("path_hint").and_then(Value::as_str),
                ),
                "set_last_event" => router.backdate_for_test(
                    as_str(&op["session_id"]),
                    clock.now() + op["relative_to_now"].as_f64().expect("relative"),
                ),
                "add_to_digest" => router.add_to_digest(
                    as_str(&op["session_id"]),
                    as_str(&op["kind"]),
                    as_str(&op["tag"]),
                    as_str(&op["neutral"]),
                    op.get("ctx").cloned().filter(|v| !v.is_null()),
                ),
                "classify" => {
                    let voices: Option<HashMap<String, String>> = op
                        .get("agent_voices")
                        .filter(|v| !v.is_null())
                        .map(|v| serde_json::from_value(v.clone()).expect("agent_voices"));
                    let decision = router.classify(
                        as_str(&op["kind"]),
                        as_str(&op["tag"]),
                        as_str(&op["session_id"]),
                        voices.as_ref(),
                        op.get("auto_voices")
                            .and_then(Value::as_bool)
                            .unwrap_or(false),
                    );
                    trace.push(serde_json::json!({
                        "action": decision.action.as_str(),
                        "label_prefix": decision.label_prefix,
                        "voice_override": decision.voice_override,
                    }));
                }
                "mode" => trace.push(Value::from(router.mode().as_str())),
                "pin" => trace.push(Value::from(router.pin(as_str(&op["session_id"])))),
                "unpin" => router.unpin(),
                "note_flush_spoken" => router.note_flush_spoken(as_str(&op["session_id"])),
                "collect_project_flushes" => {
                    let flushes = router.collect_project_flushes(
                        op.get("auto_voices")
                            .and_then(Value::as_bool)
                            .unwrap_or(true),
                        Some(clock.now()),
                    );
                    trace.push(Value::Array(flushes.iter().map(flush_json).collect()));
                }
                "force_flush_all" => {
                    let flushes = router.force_flush_all(
                        op.get("auto_voices")
                            .and_then(Value::as_bool)
                            .unwrap_or(true),
                        Some(clock.now()),
                    );
                    trace.push(Value::Array(flushes.iter().map(flush_json).collect()));
                }
                "collect_digest" => {
                    let drained = router.collect_digest();
                    trace.push(Value::Array(
                        drained
                            .iter()
                            .map(|(info, events)| {
                                serde_json::json!({
                                    "session_id": info.session_id,
                                    "events": events.iter().map(digest_json).collect::<Vec<_>>(),
                                })
                            })
                            .collect(),
                    ));
                }
                "format_digest" => trace.push(match router.format_digest(None) {
                    Some(text) => Value::from(text),
                    None => Value::Null,
                }),
                "drain_session_summary" => {
                    let summary = router.drain_session_summary(
                        as_str(&op["session_id"]),
                        op.get("include_label")
                            .and_then(Value::as_bool)
                            .unwrap_or(true),
                    );
                    trace.push(match summary {
                        Some(text) => Value::from(text),
                        None => Value::Null,
                    });
                }
                "pending_count" => trace.push(Value::from(router.pending_count())),
                "clear_pending" => trace.push(Value::from(router.clear_pending())),
                "list_active" => {
                    trace.push(serde_json::to_value(router.list_active()).expect("list_active"))
                }
                "session_info" => {
                    trace.push(match router.session_info(as_str(&op["session_id"])) {
                        None => Value::Null,
                        Some(info) => serde_json::json!({
                            "session_id": info.session_id,
                            "cwd": info.cwd,
                            "repo_name": info.repo_name,
                            "repo_confidence": info.repo_confidence,
                            "event_seq": info.event_seq,
                            "pending": info.pending_digest.len(),
                        }),
                    })
                }
                other => panic!("{name}: unknown multi_agent op {other:?}"),
            }
        }
        assert_eq!(
            Value::Array(trace),
            script["trace"],
            "multi_agent script {name}"
        );
    }
}

fn digest_json(event: &DigestEvent) -> Value {
    // The corpus records a digest event as ordered pairs, because it came out
    // of a Python dict whose key order is kind/tag/neutral/ctx/ts.
    Value::Array(vec![
        Value::Array(vec![Value::from("kind"), Value::from(event.kind.clone())]),
        Value::Array(vec![Value::from("tag"), Value::from(event.tag.clone())]),
        Value::Array(vec![
            Value::from("neutral"),
            Value::from(event.neutral.clone()),
        ]),
        Value::Array(vec![Value::from("ctx"), event.ctx.clone()]),
        Value::Array(vec![Value::from("ts"), Value::from(event.ts)]),
    ])
}

fn flush_json(flush: &heard_state::multi_agent::ProjectFlush) -> Value {
    serde_json::json!({
        "project_key": flush.project_key,
        "label": flush.label,
        "events": flush.events.iter().map(digest_json).collect::<Vec<_>>(),
        "member_session_ids": flush.member_session_ids,
        "speaker_session_id": flush.speaker_session_id,
        "voice_override": flush.voice_override,
        "is_primary": flush.is_primary,
    })
}

// ---------------------------------------------------------------------------
// project-root inference (filesystem-shaped)
// ---------------------------------------------------------------------------

/// Guard that points `HOME` somewhere disposable and puts it back.
///
/// The Python tests do `monkeypatch.setenv("HOME", …)` for the same reason: the
/// walk stops at home, and there is no way to exercise that rule without moving
/// home. These cases run in one `#[test]` each so the env change is not racing
/// another test in the same binary.
struct HomeGuard(Option<String>);

impl HomeGuard {
    fn set(path: &Path) -> Self {
        let previous = std::env::var("HOME").ok();
        std::env::set_var("HOME", path);
        Self(previous)
    }
}

impl Drop for HomeGuard {
    fn drop(&mut self) {
        match self.0.take() {
            Some(home) => std::env::set_var("HOME", home),
            None => std::env::remove_var("HOME"),
        }
    }
}

fn build_tree(root: &Path, dirs: &Value, files: &Value) {
    for dir in dirs.as_array().expect("dirs") {
        fs::create_dir_all(root.join(as_str(dir))).expect("mkdir");
    }
    for file in files.as_array().expect("files") {
        let path = root.join(as_str(file));
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("mkdir");
        }
        fs::write(&path, "").expect("touch");
    }
}

#[test]
fn project_markers_match() {
    let data = fixture("project_root.json");
    let markers: Vec<String> = serde_json::from_value(data["markers"].clone()).expect("markers");
    assert_eq!(markers, heard_state::multi_agent::PROJECT_MARKERS.to_vec());
}

#[test]
fn find_project_root_matches() {
    let data = fixture("project_root.json");
    for case in data["find_project_root"].as_array().expect("array") {
        let name = as_str(&case["name"]);
        let root = scratch(&format!("root-{name}"));
        // Symlinked temp dirs (/var -> /private/var on macOS) would make the
        // recorded relative paths unresolvable, so canonicalise up front —
        // exactly what `_walk_stop_dirs` does for HOME and for the same reason.
        let root = fs::canonicalize(&root).expect("canonical scratch");
        build_tree(&root, &case["dirs"], &case["files"]);
        let _home = case["home"]
            .as_str()
            .map(|home| HomeGuard::set(&root.join(home)));
        for query in case["queries"].as_array().expect("queries") {
            let finder = ProjectRootFinder::new();
            let raw = as_str(&query["path"]);
            let target = if raw.is_empty() {
                String::new()
            } else {
                root.join(raw).to_string_lossy().into_owned()
            };
            let found = finder.find(&target);
            let relative = found.map(|f| {
                Path::new(&f)
                    .strip_prefix(&root)
                    .map(|p| p.to_string_lossy().into_owned())
                    .unwrap_or(f)
            });
            assert_eq!(
                relative,
                opt_string(&query["expect"]),
                "{name}: find_project_root({raw:?})"
            );
        }
        let _ = fs::remove_dir_all(&root);
    }
}

#[test]
fn repo_inference_tiers_match() {
    let data = fixture("project_root.json");
    let inference = &data["repo_inference"];
    let root = scratch("infer");
    let root = fs::canonicalize(&root).expect("canonical scratch");
    build_tree(&root, &inference["dirs"], &Value::Array(vec![]));

    for case in inference["cases"].as_array().expect("cases") {
        let name = as_str(&case["name"]);
        let _home = HomeGuard::set(&root.join(as_str(&case["home"])));
        let router = MultiAgentRouter::with(
            Arc::new(ManualClock::new(1_000.0)),
            Arc::new(BasenameProjectNamer),
        );
        let cwd = root
            .join(as_str(&case["cwd"]))
            .to_string_lossy()
            .into_owned();
        let hint = case["path_hint"]
            .as_str()
            .map(|h| root.join(h).to_string_lossy().into_owned());
        router.note_event("s1", &cwd, hint.as_deref());
        let info = router.session_info("s1").expect("session");
        assert_eq!(
            info.repo_name,
            as_str(&case["expect_repo_name"]),
            "{name}: repo_name"
        );
        assert_eq!(
            u64::from(info.repo_confidence),
            case["expect_confidence"].as_u64().expect("confidence"),
            "{name}: confidence"
        );
    }

    let ladder = &inference["upgrade_ladder"];
    let _home = HomeGuard::set(&root.join(as_str(&ladder["home"])));
    let router = MultiAgentRouter::with(
        Arc::new(ManualClock::new(1_000.0)),
        Arc::new(BasenameProjectNamer),
    );
    let weak = root
        .join(as_str(&ladder["weak_cwd"]))
        .to_string_lossy()
        .into_owned();
    let strong = root
        .join(as_str(&ladder["strong_hint"]))
        .to_string_lossy()
        .into_owned();
    let mut observed: Vec<Value> = Vec::new();
    let record = |router: &MultiAgentRouter, observed: &mut Vec<Value>| {
        let info = router.session_info("s1").expect("session");
        observed.push(Value::Array(vec![
            Value::from(info.repo_name),
            Value::from(info.repo_confidence),
        ]));
    };
    router.note_event("s1", &weak, None);
    record(&router, &mut observed);
    router.note_event("s1", &weak, Some(&strong));
    record(&router, &mut observed);
    router.note_event("s1", &weak, None);
    record(&router, &mut observed);
    assert_eq!(Value::Array(observed), ladder["expect"]);

    let _ = fs::remove_dir_all(&root);
}

// ---------------------------------------------------------------------------
// spoken
// ---------------------------------------------------------------------------

#[test]
fn spoken_hashes_and_paths_match() {
    let data = fixture("spoken.json");
    assert_eq!(
        data["max_hashes"].as_u64(),
        Some(heard_state::spoken::MAX_HASHES as u64)
    );
    for case in data["hash"].as_array().expect("array") {
        let text = as_str(&case["text"]);
        assert_eq!(
            heard_state::spoken::hash_text(text),
            as_str(&case["expect"]),
            "hash of {} chars",
            text.chars().count()
        );
    }
    let dir = scratch("spoken-paths");
    let store = SpokenStore::new(&dir);
    for case in data["state_file_name"].as_array().expect("array") {
        let sid = as_str(&case["session_id"]);
        let name = store
            .state_path(sid)
            .file_name()
            .expect("file name")
            .to_string_lossy()
            .into_owned();
        assert_eq!(name, as_str(&case["expect"]), "state path for {sid:?}");
    }
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn spoken_scripts_match() {
    let data = fixture("spoken.json");
    for script in data["scripts"].as_array().expect("scripts") {
        let name = as_str(&script["name"]);
        let dir = scratch(&format!("spoken-{name}"));
        let store = SpokenStore::new(&dir);
        let sid = as_str(&script["session_id"]);
        let mut trace: Vec<Value> = Vec::new();
        for op in script["ops"].as_array().expect("ops") {
            match as_str(&op["op"]) {
                "mark_spoken" => store.mark_spoken(sid, as_str(&op["text"])),
                "is_spoken" => trace.push(Value::from(store.is_spoken(sid, as_str(&op["text"])))),
                "filter_unspoken" => {
                    let texts: Vec<String> =
                        serde_json::from_value(op["texts"].clone()).expect("texts");
                    trace.push(
                        serde_json::to_value(store.filter_unspoken(sid, &texts)).expect("filter"),
                    );
                }
                "clear" => store.clear(sid),
                "set_offset" => store.set_offset(sid, op["offset"].as_u64().expect("offset")),
                "get_offset" => trace.push(Value::from(store.get_offset(sid))),
                "has_offset" => trace.push(Value::from(store.has_offset(sid))),
                other => panic!("{name}: unknown spoken op {other:?}"),
            }
        }
        assert_eq!(Value::Array(trace), script["trace"], "spoken script {name}");
        let body = fs::read_to_string(store.state_path(sid)).ok();
        assert_eq!(
            body,
            opt_string(&script["final_file"]),
            "spoken script {name}: state file bytes"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}

#[test]
fn spoken_initialize_at_eof_matches() {
    let data = fixture("spoken.json");
    for case in data["initialize_at_eof"].as_array().expect("array") {
        let name = as_str(&case["name"]);
        let dir = scratch(&format!("spoken-eof-{name}"));
        let store = SpokenStore::new(&dir);
        let sid = as_str(&case["session_id"]);

        let transcript_path = dir.join(format!("{sid}.jsonl"));
        let target = if case["transcript"].is_null() {
            dir.join("does-not-exist.jsonl")
        } else {
            // The corpus ships pre-rendered lines, because the offset this case
            // pins IS the file's byte length — re-serialising the objects here
            // would write CPython's spacing differently and move the offset.
            let mut body = String::new();
            for line in case["transcript_lines"]
                .as_array()
                .expect("transcript_lines")
            {
                body.push_str(as_str(line));
                body.push('\n');
            }
            fs::write(&transcript_path, &body).expect("write transcript");
            assert_eq!(
                body.len() as u64,
                case["transcript_bytes"].as_u64().expect("transcript_bytes"),
                "{name}: transcript bytes differ from the corpus"
            );
            transcript_path.clone()
        };

        let existing: Vec<String> =
            serde_json::from_value(case["existing_texts"].clone()).expect("existing_texts");
        let first = store.initialize_at_eof(sid, &target, &existing);
        assert_eq!(
            first,
            case["expect_first"].as_bool().expect("expect_first"),
            "{name}: first call"
        );
        if let Some(expected) = case.get("expect_second").and_then(Value::as_bool) {
            assert_eq!(
                store.initialize_at_eof(sid, &target, &existing),
                expected,
                "{name}: second call"
            );
        }
        assert_eq!(
            store.get_offset(sid),
            case["expect_offset"].as_u64().expect("expect_offset"),
            "{name}: offset"
        );
        let probes: Vec<bool> = case["probe"]
            .as_array()
            .expect("probe")
            .iter()
            .map(|t| store.is_spoken(sid, as_str(t)))
            .collect();
        assert_eq!(
            serde_json::to_value(probes).expect("probes"),
            case["expect_spoken"],
            "{name}: dedup probes"
        );
        assert_eq!(
            fs::read_to_string(store.state_path(sid)).ok(),
            opt_string(&case["expect_file"]),
            "{name}: state file bytes"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}

// ---------------------------------------------------------------------------
// history
// ---------------------------------------------------------------------------

#[test]
fn history_scripts_produce_identical_bytes() {
    let data = fixture("history.json");
    let stamp = as_str(&data["now_iso"]).to_string();
    for script in data["scripts"].as_array().expect("scripts") {
        let name = as_str(&script["name"]);
        let dir = scratch(&format!("history-{name}"));
        let stamp = stamp.clone();
        let history = History::with_clock(&dir, Arc::new(move || stamp.clone()));
        let mut trace: Vec<Value> = Vec::new();
        let mut last_end: u64 = 0;
        for op in script["ops"].as_array().expect("ops") {
            match as_str(&op["op"]) {
                "append" => history.append(&record_of(&op["record"])),
                "append_feedback" => history.append_feedback(
                    as_str(&op["utterance_id"]),
                    as_str(&op["source"]),
                    as_str(&op["text"]),
                    op.get("kind").and_then(Value::as_str).unwrap_or("explicit"),
                ),
                "iter_all" => {
                    let limit = op.get("limit").and_then(Value::as_u64).map(|n| n as usize);
                    trace.push(Value::Array(
                        history.iter_all(limit).iter().map(record_json).collect(),
                    ));
                }
                "iter_since_checkpoint" => {
                    let (records, end) = history.iter_since_checkpoint();
                    last_end = end;
                    trace.push(serde_json::json!({
                        "records": records.iter().map(record_json).collect::<Vec<_>>(),
                        "end": end,
                    }));
                }
                "commit_offset_from_last_read" => history.write_checkpoint(last_end),
                "write_checkpoint_past_eof" => history.write_checkpoint(last_end + 999_999),
                "prune_at_last_read" => history.commit_checkpoint_and_prune(last_end),
                "prune" => {
                    history.commit_checkpoint_and_prune(op["offset"].as_u64().expect("offset"))
                }
                "read_checkpoint" => trace.push(Value::from(history.read_checkpoint())),
                other => panic!("{name}: unknown history op {other:?}"),
            }
        }
        assert_eq!(
            Value::Array(trace),
            script["trace"],
            "history script {name}"
        );
        assert_eq!(
            fs::read_to_string(history.history_path()).ok(),
            opt_string(&script["final_jsonl"]),
            "history script {name}: JSONL bytes"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}

fn record_of(value: &Value) -> heard_state::history::Record {
    record_from_fixture(value)
        .unwrap_or_else(|| panic!("a history record must be a pair list, got {value}"))
}

fn record_json(record: &heard_state::history::Record) -> Value {
    Value::Array(
        record
            .iter()
            .map(|(key, value)| Value::Array(vec![Value::from(key.clone()), pyvalue_json(value)]))
            .collect(),
    )
}

/// A [`PyValue`] back into the corpus's pair form.
fn pyvalue_json(value: &PyValue) -> Value {
    match value {
        PyValue::Null => Value::Null,
        PyValue::Bool(b) => Value::from(*b),
        PyValue::Int(i) => Value::from(*i),
        PyValue::Float(f) => Value::from(*f),
        PyValue::Str(s) => Value::from(s.clone()),
        PyValue::List(items) => Value::Array(items.iter().map(pyvalue_json).collect()),
        PyValue::Dict(pairs) => Value::Array(
            pairs
                .iter()
                .map(|(k, v)| Value::Array(vec![Value::from(k.clone()), pyvalue_json(v)]))
                .collect(),
        ),
    }
}
