//! The queue's pure decisions against the live Python.
//!
//! `fixtures/speech/speech.json` is generated by the fixture generator (not
//! included), which runs the Python reference implementation's real
//! `Daemon._enqueue_speech`, `Daemon._flush_deferred_while_mic`, `_split` and
//! `Daemon._drain_queue` (on a stub carrying only the attributes they read,
//! with the ledger-writing `_log` silenced) and records the queue after every
//! step, and whether `history.append` fired for each delivery outcome.

use std::fs;
use std::path::PathBuf;

use heard_speech::policy::{self, Queued};
use serde_json::Value;

fn corpus() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/speech/speech.json");
    serde_json::from_str(&fs::read_to_string(path).expect("speech corpus")).expect("json")
}

#[derive(Debug, Clone)]
struct Item {
    text: String,
    session: String,
    kind: String,
}

impl Queued for Item {
    fn session(&self) -> &str {
        &self.session
    }
    fn kind(&self) -> &str {
        &self.kind
    }
}

fn snapshot(q: &[Item]) -> Value {
    Value::Array(
        q.iter()
            .map(|i| serde_json::json!([i.text, i.session, i.kind]))
            .collect(),
    )
}

fn item_of(v: &Value) -> Item {
    Item {
        text: v[0].as_str().unwrap().into(),
        session: v[1].as_str().unwrap().into(),
        kind: v[2].as_str().unwrap().into(),
    }
}

#[test]
fn constants_are_the_pythons() {
    let data = corpus();
    assert_eq!(data["queue_max"], policy::QUEUE_MAX);
    assert_eq!(data["deferred_mic_max"], policy::DEFERRED_MIC_MAX);
    assert_eq!(
        data["deferred_max_age_s"].as_f64().unwrap(),
        policy::DEFERRED_MAX_AGE_S
    );
}

#[test]
fn split_matches_python() {
    let data = corpus();
    for case in data["split"].as_array().unwrap() {
        let text = case["text"].as_str().unwrap();
        let want: Vec<String> = case["out"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_owned())
            .collect();
        assert_eq!(policy::split(text), want, "{text:.60}");
    }
}

#[test]
fn enqueue_scripts_match_python_step_for_step() {
    let data = corpus();
    let scripts = data["enqueue"].as_array().unwrap();
    assert!(scripts.len() >= 9);
    for script in scripts {
        let name = script["name"].as_str().unwrap();
        let mut queue: Vec<Item> = Vec::new();
        for (i, step) in script["steps"].as_array().unwrap().iter().enumerate() {
            let op = &step["op"];
            let item = Item {
                text: op["text"].as_str().unwrap().into(),
                session: op["session"].as_str().unwrap().into(),
                kind: op["kind"].as_str().unwrap().into(),
            };
            policy::enqueue(
                &mut queue,
                item,
                op["priority"].as_bool().unwrap(),
                op["coexists"].as_bool().unwrap(),
                policy::QUEUE_MAX,
            );
            assert_eq!(snapshot(&queue), step["queue"], "{name} step {i}");
        }
    }
}

#[test]
fn flush_scripts_match_python() {
    let data = corpus();
    let now = 10_000.0;
    for case in data["flush"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let mut queue: Vec<Item> = case["queue"]
            .as_array()
            .unwrap()
            .iter()
            .map(item_of)
            .collect();
        let deferred: Vec<(Item, bool, f64)> = case["deferred"]
            .as_array()
            .unwrap()
            .iter()
            .map(|h| {
                (
                    Item {
                        text: h["text"].as_str().unwrap().into(),
                        session: h["session"].as_str().unwrap().into(),
                        kind: "tool_pre".into(),
                    },
                    h["priority"].as_bool().unwrap(),
                    now - h["age"].as_f64().unwrap(),
                )
            })
            .collect();
        let held = case["mic_active"].as_bool().unwrap()
            || case
                .get("user_speaking")
                .and_then(Value::as_bool)
                .unwrap_or(false);
        let (after_deferred, observed): (Vec<Value>, Vec<Value>) = if held {
            (
                deferred
                    .iter()
                    .map(|(i, p, _)| serde_json::json!([i.text, p]))
                    .collect(),
                Vec::new(),
            )
        } else {
            let (fresh, expired) =
                policy::split_deferred(deferred, now, policy::DEFERRED_MAX_AGE_S);
            queue.extend(fresh);
            (
                Vec::new(),
                expired
                    .iter()
                    .map(|i| {
                        serde_json::json!({"kind": "unspoken", "tag": "held_expired",
                                           "neutral": i.text,
                                           "session": {"id": i.session, "cwd": ""}})
                    })
                    .collect(),
            )
        };
        assert_eq!(snapshot(&queue), case["after_queue"], "{name}: queue");
        assert_eq!(
            Value::Array(after_deferred),
            case["after_deferred"],
            "{name}: held"
        );
        assert_eq!(
            Value::Array(observed),
            case["observed"],
            "{name}: folded into WM"
        );
    }
}

#[test]
fn history_rule_matches_python_drain_queue() {
    // `history` runs the live `Daemon._drain_queue` once per outcome and
    // records whether `history.append` fired. The rule is "not cancelled and
    // has meta" — NOT "played": failures and skips are recorded too.
    let data = corpus();
    let cases = data["history"].as_array().unwrap();
    assert!(cases.len() >= 10);
    let mut recorded_without_playing = 0;
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let cancelled = case["cancelled"].as_bool().unwrap();
        let has_meta = case["has_meta"].as_bool().unwrap();
        let appended = case["appended"].as_bool().unwrap();
        assert_eq!(
            policy::appends_history(cancelled, has_meta),
            appended,
            "{name}"
        );
        if appended && case["outcome"] != "played" {
            recorded_without_playing += 1;
        }
        if appended {
            let keys: Vec<&str> = case["record_keys"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_str().unwrap())
                .collect();
            assert_eq!(
                keys,
                [
                    "id",
                    "kind",
                    "persona",
                    "repo_name",
                    "session_id",
                    "spoken",
                    "tag",
                    "via",
                    "voice"
                ],
                "{name}: the record shape `QueuedSpeech::append_history` writes"
            );
        }
    }
    assert!(
        recorded_without_playing >= 5,
        "the corpus must pin the failed/skipped cases"
    );
}
